version: '3.9'
services:
  postgres:
    image: postgres:14.8-alpine3.18
    container_name: mego_like_db
    environment:
      - POSTGRES_DB: "${DB_NAME}"
      - POSTGRES_USER: "${DB_USER}"
      - POSTGRES_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - ./tmp/postgres:/var/lib/postgresql/data
    ports:
      - "${DB_OUTER_PORT}:${DB_PORT}"
    networks:
      - mego_network
  mego_comment:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mego-comment
    depends_on:
      - postgres
    ports:
      - "${COMMENT_SERVICE_PORT}:${COMMENT_SERVICE_PORT}"
    networks:
      - mego_network

networks:
  mego_network:
    external: true